name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer, phpstan
      
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts --no-interaction
      
      - name: Install dev dependencies for static analysis
        run: composer install --dev --no-scripts --no-interaction
        
      - name: Run static analysis
        run: composer stan
      
      - name: Run tests
        run: composer test
      
      - name: Build and tag Docker image
        run: |
          docker build -t task-manager-api:${{ github.sha }} .
          docker tag task-manager-api:${{ github.sha }} task-manager-api:latest
